"""Embedded FastAPI server for daemon monitoring."""

from src.daemon.api.app import create_api_app
from src.daemon.api.models import (
    AnalysesResponse,
    AnalysisRecordResponse,
    ConfigResponse,
    CorrelationMatrixResponse,
    DegradationHistoryResponse,
    DegradationResponse,
    EventResponse,
    ExecutionMetricsListResponse,
    FullConfigResponse,
    GamePlanResponse,
    HealthResponse,
    MarketEventsResponse,
    PositionResponse,
    PositionsResponse,
    RebalanceAllocation,
    RebalanceResponse,
    RiskHistoryResponse,
    RiskReportResponse,
    SectorRotationResponse,
    SnapshotRecord,
    SnapshotsResponse,
    StateSummaryResponse,
    WatchlistResponse,
)

__all__ = [
    "AnalysesResponse",
    "AnalysisRecordResponse",
    "ConfigResponse",
    "CorrelationMatrixResponse",
    "DegradationHistoryResponse",
    "DegradationResponse",
    "EventResponse",
    "ExecutionMetricsListResponse",
    "FullConfigResponse",
    "GamePlanResponse",
    "HealthResponse",
    "MarketEventsResponse",
    "PositionResponse",
    "PositionsResponse",
    "RebalanceAllocation",
    "RebalanceResponse",
    "RiskHistoryResponse",
    "RiskReportResponse",
    "SectorRotationResponse",
    "SnapshotRecord",
    "SnapshotsResponse",
    "StateSummaryResponse",
    "WatchlistResponse",
    "create_api_app",
]
